name: Rebuild

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master

jobs:
  rebuild:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup poetry
        run: pipx install poetry

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: poetry

      - name: install
        run: poetry install --sync

      - name: rebuild
        run: poetry run build

      - name: publish
        uses: EndBug/add-and-commit@v9
        with:
          add: 'docs'
          default_author: github_actions
          message: 'repository update'
